### ISSUE TITLE
File resources/cyber-duck/silverstripe-linkitemfield/assets/js/linkitemfield.js does not exist

### ISSUE THREAD

**Issue by dmcb** [Cyber-Duck/Silverstripe-LinkItemField#1]
Silverstripe-LinkItemField was working for me on SS4, but now it's not, so I suspect the latest version of SS (4.0.3) has changed something to this module's detriment, because now when I log in to the admin error, it crashes with the following fatal error:

`[Emergency] Uncaught InvalidArgumentException: File resources/cyber-duck/silverstripe-linkitemfield/assets/js/linkitemfield.js does not exist`

**Comment by marek-eh** [comment]
Same issue with SS 4.1.0.

I was able to fix for my local to change some paths in: vendor/cyber-duck/silverstripe-linkitemfield/_config/cms.yml

Change from "resources/cyber-duck/...." to "vendor/cyber-duck/.... "

Thia fixed my admin panel issue.

**Comment by ramono** [comment]
Merged a PR which fixes the issue with the resources
